name: CI

# Run this workflow every time a new commit pushed to master
on: push

jobs:
  build:
    # Name the Job
    name: Build
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    env:
      working-directory: ./test_homework

    steps:
      - name: Install boost
        run: sudo apt-get install libboost-test-dev -y

      - name: Configure apt
        run: echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list

      - name: Update
        run: sudo apt-get update -qq 
        
      - name: Generate build number
        uses: einaregilsson/build-number@v2 
        with:
          token: ${{secrets.github_token}}      
     
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"

      # Checks out a copy of repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Configure
        working-directory: ${{env.working-directory}}
        run: mkdir build && cd build && cmake ..

      - name: Build project
        working-directory: ${{env.working-directory}}
        run: cmake --build build --config Release

      - name: Print directory files
        working-directory: ${{env.working-directory}}/build
        run: echo "Files in bild dir `ls`"

      - name: Publish Releases
        uses: bpicode/github-action-upload-bintray@master
        with:
          file: helloworld-0.0.$BUILD_NUMBER-Linux.deb
          api_user: ${{ secrets.BINTRAY_USER }}
          api_key: ${{ secrets.BINTRAY_API_KEY }}
          repository_user: ${{ secrets.BINTRAY_USER }}
          repository: OTUS_Homeworks
          package: Test_package
          version: 0.0.$BUILD_NUMBER
          publish: 1
          deb_distribution: trusty
          deb_component: main
          deb_architecture: amd64
