name: Build and upload allocators

# Run this workflow every time a new commit pushed to master
on: 
  push:
    paths:
      - "allocators/**"

jobs:
  build:
    # Name the Job
    name: Build
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    env:
      working-directory: ./allocators

    steps:
      - name: Configure apt
        run: echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list

      - name: Update
        run: sudo apt-get update -qq 
        
      - name: Generate build number
        uses: einaregilsson/build-number@v2 
        with:
          token: ${{secrets.github_token}}      
     
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"

      - name: Set an environment variable
        run: echo "build_number=$BUILD_NUMBER" >> $GITHUB_ENV

      # Checks out a copy of repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build project
        working-directory: ${{env.working-directory}}
        run: |
            cmake .
            cmake --build .
            cmake --build . --target test
            cmake --build . --target package

      - name: Publish Releases
        uses: bpicode/github-action-upload-bintray@master
        with:
          file: ${{env.working-directory}}/my_allocator-0.0.${{ env.build_number }}-Linux.deb
          api_user: ${{ secrets.BINTRAY_USER }}
          api_key: ${{ secrets.BINTRAY_API_KEY }}
          repository_user: ${{ secrets.BINTRAY_USER }}
          repository: OTUS_Homeworks
          package: My_allocator_package
          version: 0.0.${{ env.build_number }}
          publish: 1
          deb_distribution: trusty
          deb_component: main
          deb_architecture: amd64
